drop database if exists dbAGROCONTROL;

CREATE DATABASE DBAGROCONTROL;
USE DBAGROCONTROL;

CREATE TABLE CLIENTE (
IDCLIENTE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(100),
EMAIL VARCHAR(100),
TELEFONE char(20),
CELULAR char(20),
RUA VARCHAR(100),
NUMERO INT,
BAIRRO VARCHAR(100),
CIDADE VARCHAR(100)
);

CREATE TABLE ANIMAL (
IDANIMAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
IDCLIENTE INT NOT NULL,
NOME VARCHAR(100),
RACA VARCHAR(100),
GENERO char(1),
TIPO VARCHAR(50),
OBSERVACAO TEXT,
CONSTRAINT FK_ANIMAL_CLIENTE FOREIGN KEY(IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE)
);

CREATE TABLE RACA (
IDRACA INT NOT NULL AUTO_INCREMENT primary KEY,
NOME VARCHAR (100)
);

CREATE TABLE TIPO (
IDTIPO INT NOT NULL AUTO_INCREMENT primary KEY,
NOME VARCHAR (100)
);

select * from cliente;
update cliente set cidade = "São José" where cidade = "São Jose";
select * from animal;
